### ISSUE TITLE
Frontend flow for name selection

### ISSUE THREAD

**Issue by lsankar4033** [personaelabs/nym#8]
as seen here: https://twitter.com/personae_labs/status/1637913919124803584?s=20

there are 3 ways a user can post:
1. nym
2. ENS name 
    a. or '0x.....' from web3 wallet
3. pseudonymous nouner (as in heyanoun)
figure out the flow for users to designate how they post

users can only post with a connected web3 wallet (we don't have to worry about the situation where one isn't connected)

if user is a nouner (detected from wallet), have the option to do 1 or 3 above, otherwise just 2

assume previous nyms are stored in localstorage (so that can be re-selected easily)

**Comment by lsankar4033** [comment]
salvino + tony - top-level toggle probably makes sense. you have 1 identity from which you post (that you can change at top-level)

**Comment by lsankar4033** [comment]
other misc notes:
- creating a new nym is a fast operation (ECDSA sig + poseidon hash), but requires `signTypedData` from web3 wallet (so user interaction)
- selecting an old nym requires no additional interaction (assuming nym sig is in localstorage)
- generate proof + sig *only* at post time. proving is slightly longer operation (~3s w/spartan-ecdsa)
- signatures for each nym stored in localstorage; if these leak, others can impersonate as these nyms! i.e. having the signature for a nym means one can impersonate the nym
- leaking signature does *not* compromise user wallet

**Comment by lsankar4033** [comment]
spectrum of possible interaction design:

top-level identity only < ---------- top-level identity + post-level identity -------> only post-level identity

**Comment by cha0sg0d** [comment]
> 

@lsankar4033 re: storing data in localStorage, I just had a thought: 

What happens if we just store `nyms` in localStorage, not `nymSignatures`? If I'm understanding the flow correctly, each time a user makes a post, they would have to make two signatures:
1. Sign their `nymCode` for the proof input
2. Sign their `contentData` for the proof input.

Pros:
- A nym cannot be promised if localStorage is hacked, because we only store public information as an aide to users who want to know which nyms they've made.
Cons:
- An extra wallet interaction for each post

IMO, the Cons win here and we should store in intermediate `nymSignature` in localStorage. We need to reduce friction as much as possible.

Perhaps down the road we can have a power user `uber-private` mode where we only store full nyms in localStorage and you just have to generate the `nymSignature` each time.

Just documenting here as a possible option.

**Comment by cha0sg0d** [comment]
Closed by #91
